RockstarsIT/RockstarsIT/Models/SurveyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RockstarsIT.Models;

public class SurveyViewModel
{
    public int Id { get; set; }
    [Required]
    public string Title { get; set; }
    [Required]
    public string Description { get; set; }
    public List<MinimalSquadViewModel> AllSquads { get; set; } = new();
    public List<int> SelectedSquadIds { get; set; } = new();

    public List<MinimalSquadViewModel> Squads { get; set; }
}

RockstarsIT/RockstarsIT/Controllers/AnswerController.cs
using Microsoft.AspNetCore.Mvc;
using RockstarsIT_BLL;
using RockstarsIT_BLL.Dto;
using RockstarsIT_BLL.Interfaces;
using RockstarsIT.Models;

namespace RockstarsIT.Controllers
{
    public class AnswerController : Controller
    {
        private readonly SurveyService _surveyService;

        public AnswerController(SurveyService surveyService)
        {
            _surveyService = surveyService;
        }


        public IActionResult Index(int surveyId)
        {
            var mockFullSurveyViewModel = new FullSurveyViewModel
            {
                Id = 1,
                Title = "Company Culture Survey 2024",
                Description = "Annual survey to measure employee satisfaction and company culture",
                Questions = new List<QuestionViewModel>
                {
                    new QuestionViewModel
                    {
                        Id = 1,
                        Title = "How satisfied are you with the company's work-life balance?",
                        Answers = new List<AnswerViewModel>
                        {
                            new AnswerViewModel
                            {
                                Id = 1,
                                Result = AnswerResult.LIKE,
                                Feedback = "Great flexibility with working hours and remote work options"
                            },
                            new AnswerViewModel
                            {
                                Id = 2,
                                Result = AnswerResult.NEUTRAL,
                                Feedback = "Generally good, but could use more flexibility during peak times"
                            }
                        }
                    },
                    new QuestionViewModel
                    {
                        Id = 2,
                        Title = "How would you rate the professional growth opportunities?",
                        Answers = new List<AnswerViewModel>
                        {
                            new AnswerViewModel
                            {
                                Id = 3,
                                Result = AnswerResult.LIKE,
                                Feedback = "Excellent training programs and mentorship opportunities"
                            },
                            new AnswerViewModel
                            {
                                Id = 4,
                                Result = AnswerResult.DISLIKE,
                                Feedback = "Would like to see more structured career progression paths"
                            }
                        }
                    },
                    new QuestionViewModel
                    {
                        Id = 3,
                        Title = "Rate the effectiveness of team collaboration tools",
                        Answers = new List<AnswerViewModel>
                        {
                            new AnswerViewModel
                            {
                                Id = 5,
                                Result = AnswerResult.LIKE,
                                Feedback = "Tools are good but we need better integration between systems"
                            }
                        }
                    }
                },
                Squads = new List<SquadViewModel>
                {
                    new SquadViewModel
                    {
                        Id = 1,
                        Name = "NS Developers team"
                    },
                    new SquadViewModel
                    {
                        Id = 2,
                        Name = "Rabobank Software Developers"
                    },
                    new SquadViewModel
                    {
                        Id = 3,
                        Name = "NS Developers"
                    }
                }
            };

            return View(mockFullSurveyViewModel);
        }

        public IActionResult Chart(int surveyId)
        {
            FullSurveyDto? survey = _surveyService.GetSurveyById(surveyId);

            if (survey == null)
            {
                return NotFound();
            }

            FullSurveyViewModel fullSurveyViewModel = new FullSurveyViewModel
            {
                Id = survey.Id,
                Title = survey.Title,
                Description = survey.Description,
                Questions = survey.Questions.Select(q => new QuestionViewModel
                {
                    Id = q.Id,
                    Title = q.Title,
                    Answers = q.Answers.Select(a => new AnswerViewModel
                    {
                        Id = a.Id,
                        Result = a.Result,
                    }).ToList()
                }).ToList(),
                Squads = survey.Squads.Select(s => new SquadViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                }).ToList()
            };

            return View(fullSurveyViewModel);
        }
    }
}

RockstarsIT/RockstarsIT/Controllers/SurveyController.cs
using Microsoft.AspNetCore.Mvc;
using RockstarsIT_BLL;
using RockstarsIT_BLL.Dto;
using RockstarsIT.Models;
using System.Data;
using System.ComponentModel.Design;

namespace RockstarsIT.Controllers;

public class SurveyController : Controller
{
    private readonly SurveyService _surveyService;
    private readonly QuestionService _questionService;
    private readonly SquadService _squadService;
    private readonly EmailService _emailService;


    // Injecting DbContext in the constructor
    public SurveyController(SurveyService surveyService, QuestionService questionService, SquadService squadService, EmailService emailService)
    {
        _surveyService = surveyService;
        _questionService = questionService;
        _squadService = squadService;
        _emailService = emailService;
    }
    
    // GET
    public IActionResult Index(int? squadId)
    {
        List<SurveyDto> allSurveys = _surveyService.GetAllSurveys();
        List<SquadDto> allSquads = _squadService.GetSquads();
        

        HashSet<MinimalSquadViewModel> squads = new HashSet<MinimalSquadViewModel>
            {
                new MinimalSquadViewModel() { Id = 0, Name = "Geen squads" }
            };
        foreach (SquadDto squad in allSquads)
        {
            squads.Add(new MinimalSquadViewModel
            {
                Id = squad.Id,
                Name = squad.Name
            });
        }
        List<SurveyDto> filteredSurveys = allSurveys;

        string selectedSquadName = null;
        if (squadId.HasValue && squadId.Value != 0)
        {
            filteredSurveys = allSurveys.Where(s => s.Squads.Any(sq => sq.Id == squadId.Value)).ToList();
            selectedSquadName = squads.FirstOrDefault(s => s.Id == squadId.Value)?.Name;
        }

        if (selectedSquadName == null)
        {
            selectedSquadName = "Kies een squad";
        }


        List<SurveyViewModel> surveyViewModels = filteredSurveys.Select(s =>
        {
            return new SurveyViewModel
            {
                Id = s.Id,
                Title = s.Title,
                Description = s.Description,
                Squads = s.Squads.Select(sq => new MinimalSquadViewModel()
                {
                    Name = sq.Name,
                    Id = sq.Id
                }).ToList()
            };
        }).ToList();

        ViewBag.Squads = squads.ToList();
        ViewBag.SelectedSquadName = selectedSquadName;
        return View(surveyViewModels);
    }

    public IActionResult Details(int id)
    {
        FullSurveyDto? survey = _surveyService.GetSurveyById(id);
        
        if (survey == null)
        {
            return NotFound();
        }
        
        FullSurveyViewModel surveyViewModel = new FullSurveyViewModel()
        {
            Id = survey.Id,
            Title = survey.Title,
            Description = survey.Description,
            Questions = survey.Questions.Select(q => new QuestionViewModel
            {
                Id = q.Id,
                Title = q.Title
            }).ToList(),
            Squads = survey.Squads.Select(s => new SquadViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description
            }).ToList()
        };
        
        return View(surveyViewModel);
    }

    public IActionResult SendEmail(int surveyId) {
        try
        {
            _emailService.SendEmails(surveyId);
            
            TempData["Message"] = "Emails zijn succesvol verstuurd";
        
            return RedirectToAction("Details", new { id = surveyId });
        }
        catch (Exception e)
        {
            TempData["Message"] = "Er is iets fout gegaan bij het versturen van de emails";
            return RedirectToAction("Details", new { id = surveyId });
        }
    } 

    public IActionResult Create()
    {
        return View();
    }
    

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CreateEditSurveyViewModel survey)
    {
        try 
        {
            if (!ModelState.IsValid)
            {
                return View(survey);
            }

            CreateEditSurveyDto surveyDto = new()
            {
                Title = survey.Title,
                Description = survey.Description,
            };

            int surveyId = _surveyService.CreateSurvey(surveyDto);

            foreach (QuestionViewModel question in survey.Questions)
            {
                CreateEditQuestionDto createEditQuestionDto = new CreateEditQuestionDto()
                {
                    Title = question.Title,
                    SurveyId = surveyId
                };
                
                _questionService.CreateQuestion(createEditQuestionDto);
            }
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Er is iets fout gegaan bij het opslaan van de survey en vragen.";
            return View(survey);
        }

        return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {

        try
        {
            FullSurveyDto? surveyDto = _surveyService.GetSurveyById(id);


            if (surveyDto == null)
            {
                return NotFound();
            }
            
            List<SquadDto> allSquads = _squadService.GetSquads();

            // Filter out squads that are already on the survey
            List<SquadDto> filteredSquads = allSquads.Where(s => !surveyDto.Squads.Any(sq => sq.Id == s.Id)).ToList();

            CreateEditSurveyViewModel surveyViewModel = new CreateEditSurveyViewModel()
            {
                Id = surveyDto.Id,
                Title = surveyDto.Title,
                Description = surveyDto.Description,
                Questions = surveyDto.Questions.Select(q => new QuestionViewModel
                {
                    Id = q.Id,
                    Title = q.Title
                }).ToList(),
                Squads = surveyDto.Squads.Select(s => new SquadViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description
                }).ToList(),
                AllSquads = filteredSquads.Select(s => new MinimalSquadViewModel()
                {
                    Id = s.Id,
                    Name = s.Name,
                }).ToList(),
            };
            return View(surveyViewModel);

        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Er is iets fout gegaan bij het ophalen van de squad";
            return View();
        }
    }

    // POST: Squads/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(CreateEditSurveyViewModel surveyViewModel)
    {
        try
        {
            if (ModelState.IsValid)
            {
                CreateEditSurveyDto createEditSurveyDto = new CreateEditSurveyDto()
                {
                    Title = surveyViewModel.Title,
                    Description = surveyViewModel.Description,
                    SquadIds = surveyViewModel.SelectedSquadIds,
                    SquadIdsToDelete = surveyViewModel.SquadIdsToDelete
                };

                _surveyService.EditSurvey(surveyViewModel.Id, createEditSurveyDto);

                // Get the original survey to compare questions
                var originalSurvey = _surveyService.GetSurveyById(surveyViewModel.Id);
                var existingQuestionIds = originalSurvey.Questions.Select(q => q.Id).ToList();
                var updatedQuestionIds = surveyViewModel.Questions.Where(q => q.Id != 0).Select(q => q.Id).ToList();

                // Find questions that were deleted (exist in database but not in the form)
                var deletedQuestionIds = existingQuestionIds.Except(updatedQuestionIds);

                // Delete questions that were removed
                foreach (var questionId in deletedQuestionIds)
                {
                    _questionService.DeleteQuestion(questionId);
                }

                // Handle remaining questions
                if (surveyViewModel.Questions != null)
                {
                    foreach (var question in surveyViewModel.Questions)
                    {
                        CreateEditQuestionDto createEditQuestionDto = new CreateEditQuestionDto()
                        {
                            Title = question.Title,
                            SurveyId = surveyViewModel.Id,
                        };

                        // If Id is 0, it's a new question
                        if (question.Id == 0)
                        {
                            _questionService.CreateQuestion(createEditQuestionDto);
                        }
                        else
                        {
                            _questionService.EditQuestion(question.Id, createEditQuestionDto);
                        }
                    }
                }

                return RedirectToAction("Index");
            }

            return RedirectToAction("Details", new { id = surveyViewModel.Id });
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Er is iets fout gegaan bij het opslaan van de survey en vragen.";
            return View(surveyViewModel);
        }
    }

    public IActionResult Delete(int id)
    {
        try
        {
            _surveyService.DeleteSurvey(id);
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["ErrorMessage"] = "Er is iets fout gegaan bij het verwijderen van de survey.";
            return RedirectToAction("Index");
        }
    }
}

RockstarsIT/RockstarsIT/Views/Survey/Create.cshtml
@model CreateEditSurveyViewModel

@{
    ViewBag.Title = "Nieuwe health check";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />


<div class="create-container">
    <div class="inner-container">
        <h1>Nieuwe Health Check Aanmaken</h1>
        
        <hr />
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="text-danger">@TempData["ErrorMessage"]</div>
            }
            <div>
                <label asp-for="Title" class="control-label">Titel</label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Description" class="control-label">Omschrijving</label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Vragen</label>
                <div id="questions-container"> </div>
                <button type="button" id="add-question" class="btn btn-primary mt-2">Voeg Vraag Toe</button>
            </div>

            <button class="btn btn-primary mt-2" style="width: 100%; margin-top: 50px !important;" type="submit">Health Check Aanmaken</button>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const container = document.getElementById("questions-container");
            const addQuestionButton = document.getElementById("add-question");

            // Unique identifier for questions
            let questionIndex = 0;

            // Add a new question input
            addQuestionButton.addEventListener("click", function () {
                const uniqueId = `question-${questionIndex}`; // Unique ID for this question
                const questionDiv = document.createElement("div");
                questionDiv.classList.add("form-group", "mt-2");
                questionDiv.setAttribute("data-id", uniqueId); // Assign unique ID

                questionDiv.innerHTML = `
                <div class="flex flex-row gap-2">
                    <input type="text" name="Questions[${questionIndex}].Title" asp-for="Questions[${questionIndex}].Title" class="form-control question-title" placeholder="Vraag ${questionIndex + 1}" />
                    <button type="button" class="btn btn-danger mt-2 remove-question">Verwijder Vraag</button>
                </div>
                `;

                container.appendChild(questionDiv);
                questionIndex++;
            });

            // Handle question removal
            container.addEventListener("click", function (event) {
                if (event.target.classList.contains("remove-question")) {
                    const questionDiv = event.target.closest(".form-group");
                    questionDiv.remove();

                    // After removal, reindex all questions
                    const remainingQuestions = container.querySelectorAll(".form-group");
                    remainingQuestions.forEach((question, newIndex) => {
                        const input = question.querySelector(".question-title");
                        input.name = `Questions[${newIndex}].Title`;
                        input.placeholder = `Vraag ${newIndex + 1}`;
                    });

                    // Update questionIndex to reflect the new total count
                    questionIndex = remainingQuestions.length;
                }
            });
        });
    </script>
}

RockstarsIT/RockstarsIT/Views/Survey/Delete.cshtml
@model RockstarsIT.Models.SurveyViewModel
@{
    ViewData["Title"] = "Delete";
}

<h3>Weet je zeker dat je @Model.Title wilt verwijderen?</h3>

<div>
    <hr/>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Bevestigen" class="btn btn-danger" /> |
        <a asp-action="Index">Terug</a>
    </form>
</div>

RockstarsIT/RockstarsIT/Views/Survey/Details.cshtml
@model FullSurveyViewModel

@{
    ViewBag.Title = "title";
}
<link rel="stylesheet" href="~/css/Survey.css/Details.css" />
@* <h2>Dit is survey van @Html.DisplayFor(model => model.Title)</h2> *@
@* *@
@* *@
@* @Html.ActionLink("SendEmail", "SendEmail",  "Survey", new  { id = 2 }, null) *@


<div class="details-container">
    <div class="inner-container">
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-info" role="alert">
                @TempData["Message"]
            </div>
        }
        <h4>@Model.Title</h4>

        <hr/>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="text-danger">@TempData["ErrorMessage"]</div>
            }
            <div class="form-group">
                <label asp-for="Title" class="control-label">Naam</label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <a class="button button-secondary" asp-controller="Answer" asp-action="Index" asp-route-surveyId="@Model.Id">Bekijk antwoorden</a>
            <a class="button button-secondary" asp-controller="Answer" asp-action="Chart" asp-route-surveyId="@Model.Id">Bekijk grafiek</a>
            <h5>Squads</h5>
            <div style="display: flex; flex-direction: column; gap: 15px;">
                @foreach (var squad in Model.Squads)
                {
                    <div class="form-group">
                        <p>@squad.Name</p>
                    </div>
                }
            </div>
        </form>
        <a class="button button-primary button-full" asp-action="SendEmail" asp-route-surveyId="@Model.Id">Verstuur Email</a>
        <a class="button button-secondary button-full" asp-action="Index">Terug</a>
    </div>
</div>

RockstarsIT/RockstarsIT/Views/Survey/Edit.cshtml
@model CreateEditSurveyViewModel

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />

<div class="edit-container">
    <div class="inner-container">
        <h4>Bewerk @Model.Title</h4>
        
        <hr/>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="text-danger">@TempData["ErrorMessage"]</div>
            }
            <div class="form-group">
                <label asp-for="Title" class="control-label">Naam</label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <h5>Vragen</h5>
            <div class="form-group">
                <div id="questions-container">
                    @for (int i = 0; i < Model.Questions.Count; i++)
                    {
                        <div class="form-group">
                            <input asp-for="Questions[i].Title" class="form-control"/>
                            <button type="button" class="btn btn-danger mt-2 remove-question">Verwijder Vraag</button>
                            <input type="hidden" asp-for="Questions[i].Id"/>
                        </div>
                    }
                </div>
            </div>
            <button type="button" id="add-question" class="btn btn-secondary mt-2">Voeg Vraag Toe</button>
            <div class="form-group">
                <input type="submit" value="Opslaan" class="btn  btn-warning text-white mt-2" style="width: 100%; margin-top: 50px !important;"/>
            </div>
            <div class="form-group">
                <label asp-for="SelectedSquadIds" class="control-label">Add new Squads</label>
                <select asp-for="SelectedSquadIds" class="form-control" asp-items="@(new SelectList(Model.AllSquads.Where(s => !Model.SelectedSquadIds.Contains(s.Id)), "Id", "Name"))"></select>
                <span asp-validation-for="SelectedSquadIds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SquadIdsToDelete" class="control-label">Remove Squad</label>
                <select asp-for="SquadIdsToDelete" class="form-control" asp-items="@(new SelectList(Model.Squads?.Where(s => !Model.SelectedSquadIds.Contains(s.Id)) ?? Enumerable.Empty<SquadViewModel>(), "Id", "Name"))"></select>
                <span asp-validation-for="SquadIdsToDelete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" style="width: 100%;" onclick="return confirm('Weet je zeker dat je deze health check wilt verwijderen?');">Verwijder Health check</a>
            </div>
            <input type="hidden" asp-for="Id" />
        </form>
        <a class="btn bg-black text-white" asp-action="Index">Terug</a>
    </div>
</div>


@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const container = document.getElementById("questions-container");
            const addQuestionButton = document.getElementById("add-question");

            let questionIndex = @Model.Questions.Count;

            addQuestionButton.addEventListener("click", function () {
                const questionDiv = document.createElement("div");
                questionDiv.classList.add("form-group", "mt-2");

                questionDiv.innerHTML = `
                    <div class="flex flex-row gap-2">
                        <input type="text" name="Questions[${questionIndex}].Title" class="form-control question-title" placeholder="Vraag ${questionIndex + 1}" />
                        <button type="button" class="btn btn-danger mt-2 remove-question">Verwijder Vraag</button>
                        <input type="hidden" name="Questions[${questionIndex}].Id" value="0" />
                    </div>
                `;

                container.appendChild(questionDiv);
                questionIndex++;
            });

            // Function to reindex questions
            function reindexQuestions() {
                const remainingQuestions = container.querySelectorAll(".form-group");
                remainingQuestions.forEach((question, index) => {
                    const titleInput = question.querySelector("input[type='text']");
                    const idInput = question.querySelector("input[type='hidden']");
                    
                    titleInput.name = `Questions[${index}].Title`;
                    titleInput.placeholder = `Vraag ${index + 1}`;
                    idInput.name = `Questions[${index}].Id`;
                });
                questionIndex = remainingQuestions.length;
            }

            // Handle question removal using event delegation
            container.addEventListener("click", function(event) {
                const removeButton = event.target.closest(".remove-question");
                if (removeButton) {
                    const questionDiv = event.target.closest(".form-group");
                    questionDiv.remove();
                    reindexQuestions();
                }
            });
        });
    </script>
}

RockstarsIT/RockstarsIT/Views/Survey/Index.cshtml
@model IEnumerable<SurveyViewModel>

@{
    ViewData["Title"] = "Health check overzicht";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />
<div class="header-container">
    <h2>Health Checks</h2>
    <a asp-action="Create" class="button button-primary">TOEVOEGEN</a>
</div>
<div class="dropdown">
    <button class="button button-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        @ViewBag.SelectedSquadName
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        @if (ViewBag.Squads != null)
        {
            foreach (var squad in ViewBag.Squads)
            {
                <li>
                    <a class="dropdown-item text-black text-decoration-none" href="#" data-squad-id="@squad.Id">@squad.Name</a>
                </li>
            }
        }
        else
        {
            <li><a class="dropdown-item" href="#">Geen Squads beschikbaar</a></li>
        }
    </ul>
</div>

<div class="grid">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <div class="card">
                <a class="plus-button" asp-action="Edit" asp-route-id="@item.Id" aria-label="Add Item">+</a>
                <div class="card-header">
                    <h2>@item.Title</h2>
                </div>
                <div class="card-body">
                    <p>@item.Description</p>
                    <div class="actions">
                        <a asp-action="Details" asp-route-id="@item.Id" class="button button-primary btn-sm">Details</a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="button button-secondary">Bewerken</a>
                    </div>
                </div>
            </div>
    }
    }
    else
    {
        <p>Geen health check gevonden.</p>
    }
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dropdownItems = document.querySelectorAll('.dropdown-item');
        const dropdownButton = document.getElementById('dropdownMenuButton');

        dropdownItems.forEach(item => {
            item.addEventListener('click', function () {
                const squadId = this.getAttribute('data-squad-id');
                const squadName = this.textContent;

                // Werk de knoptekst bij
                dropdownButton.textContent = squadName;

                // Stuur de gebruiker door naar de gefilterde pagina
                window.location.href = `?squadId=${squadId}`;
            });
        });
    });
</script>