RockstarsIT/RockstarsIT/Models/SquadViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RockstarsIT.Models;
    
public class SquadViewModel : MinimalSquadViewModel
{

    [Required]
    public string Description { get; set; }
    
    public CompanyViewModel? Company { get; set; }
}

RockstarsIT/RockstarsIT/Controllers/SquadController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using RockstarsIT_BLL;
using RockstarsIT_BLL.Dto;
using RockstarsIT.Models;
using System.Text.Json;
namespace RockstarsIT.Controllers
{
    public class SquadController : Controller
    {

        private readonly SquadService _squadService;
        private readonly CompanyService _companyService;
        private readonly UserService _userService;

        public SquadController(SquadService squadService, CompanyService companyService, UserService userService)
        {
            _squadService = squadService;
            _companyService = companyService;
            _userService = userService;
        }

        // GET: Squads
        public async Task<IActionResult> Index(int? companyId)
        {
            List<SquadDto> allSquads = _squadService.GetSquads();
            List<CompanyDto> allCompanies = _companyService.GetAllCompanies();

            HashSet<CompanyViewModel> companies = new HashSet<CompanyViewModel>
            {
                new CompanyViewModel { Id = 0, Name = "Geen bedrijf" }
            };

            foreach (CompanyDto company in allCompanies)
            {
                companies.Add(new CompanyViewModel
                {
                    Id = company.Id,
                    Name = company.Name
                });
            }

            List<SquadDto> filteredSquads = allSquads;

            string selectedCompanyName = null;
            if (companyId.HasValue && companyId.Value != 0)
            {
                filteredSquads = allSquads.Where(s => s.Company != null && s.Company.Id == companyId.Value).ToList();
                selectedCompanyName = companies.FirstOrDefault(c => c.Id == companyId.Value)?.Name;
            }

            if (selectedCompanyName == null)
            {
                selectedCompanyName = "Kies een bedrijf";
            }

            List<SquadViewModel> squadViewModels = filteredSquads.Select(s =>
            {
                return new SquadViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    Company = s.Company != null ? new CompanyViewModel
                    {
                        Id = s.Company.Id,
                        Name = s.Company.Name
                    } : null
                };
            }).ToList();

            ViewBag.Companies = companies.ToList();
            ViewBag.SelectedCompanyName = selectedCompanyName;
            return View(squadViewModels);
        }

        // GET: Squads/Details/5
        public IActionResult Details(int id)
        {
            try
            {
                SquadDto squadDto = _squadService.GetSquadById(id);

                if (squadDto == null)
                {
                    return NotFound();
                }

                SquadViewModel squadViewModel = new SquadViewModel()
                {
                    Id = squadDto.Id,
                    Name = squadDto.Name,
                    Description = squadDto.Description
                };

                return View(squadViewModel);
            }
            catch (Exception e)
            {
                return NotFound();
            }
        }

        // GET: Squads/Create
        public IActionResult Create()
        {
            return View(new CreateEditSquadViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public UserDto? CreateUser(CreateEditSquadViewModel squadViewModel)
        {
            if (squadViewModel.NewUser == null)
            {
                return null;
            }

            // check if email is valid
            string email = squadViewModel.NewUser.Email;
            if (!new EmailAddressAttribute().IsValid(email))
            {
                ViewData["ErrorMessage"] = "Email is not valid";
                return null;
            }

            UserDto? user = _userService.CreateUser(email);

            return user;
        }

        // POST: Squads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateEditSquadViewModel squadViewModel, string emails)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Deserialize the emails JSON string
                    List<string> emailList = JsonSerializer.Deserialize<List<string>>(emails ?? "[]");

                    List<string> userIds = new List<string>();

                    foreach (string email in emailList)
                    {
                        UserDto? user = _userService.CreateUser(email);

                        if (user == null)
                        {
                            continue;
                        }

                        userIds.Add(user.Id);
                    }


                    CreateEditSquadDto squadDto = new CreateEditSquadDto()
                    {
                        Name = squadViewModel.Name,
                        Description = squadViewModel.Description,
                        UserIds = userIds
                    };

                    _squadService.CreateSquad(squadDto);
                    return RedirectToAction("Index");
                }
                return View(squadViewModel);
            }
            catch (DuplicateNameException ex)
            {
                ViewData["ErrorMessage"] = "Er bestaat al een squad met deze naam";
                return View(squadViewModel);
            }
            catch (Exception e)
            {
                ViewData["ErrorMessage"] = "Er is iets fout gegaan bij het aanmaken van de squad";
                return View(squadViewModel);
            }
        }

        // GET: Squads/Edit/5
        public IActionResult Edit(string id)
        {
            try
            {
                SquadWithUsersDto? squadDto = _squadService.GetSquadById(int.Parse(id));
                List<CompanyDto> companies = _companyService.GetAllCompanies();


                if (squadDto == null)
                {
                    return NotFound();
                }


                CreateEditSquadViewModel squadViewModel = new CreateEditSquadViewModel()
                {
                    Id = squadDto.Id,
                    Name = squadDto.Name,
                    Description = squadDto.Description,
                    Companies = companies.Select(s => new CompanyViewModel()
                    {
                        Id = s.Id,
                        Name = s.Name,
                    }).ToList(),
                    Users = squadDto.Users.Select(u => new UserViewModel()
                    {
                        Id = u.Id,
                        Email = u.Email
                    }).ToList(),
                    Company = squadDto.Company != null ? new CompanyViewModel()
                    {
                        Id = squadDto.Company.Id,
                        Name = squadDto.Company.Name
                    } : null
                };
                return View(squadViewModel);

            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Er is iets fout gegaan bij het ophalen van de squad";
                return View();
            }
        }

        // POST: Squads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CreateEditSquadViewModel squadViewModel, string emails)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Deserialize the emails JSON string
                    List<string> emailList = JsonSerializer.Deserialize<List<string>>(emails ?? "[]");

                    List<string> userIds = new List<string>();

                    foreach (string email in emailList)
                    {
                        UserDto? user = _userService.CreateUser(email);
                        if (user == null)
                        {
                            continue;
                        }
                        userIds.Add(user.Id);
                    }

                    CreateEditSquadDto squadDto = new CreateEditSquadDto()
                    {
                        Name = squadViewModel.Name,
                        Description = squadViewModel.Description,
                        UserIds = userIds
                    };

                    _squadService.EditSquad(squadViewModel.Id, squadDto);
                    return RedirectToAction("Index");
                }

                return View(squadViewModel);
            }
            catch (DuplicateNameException ex)
            {
                TempData["ErrorMessage"] = "Er bestaat al een squad met deze naam";
                return RedirectToAction("Edit", new { id = squadViewModel.Id });
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "Er is iets fout gegaan bij het bewerken van de squad";
                return RedirectToAction("Edit", new { id = squadViewModel.Id });
            }
        }

        // GET: Squads/Delete/5
        public IActionResult Delete(string id)
        {

            try
            {
                SquadDto? squadDto = _squadService.GetSquadById(int.Parse(id));

                if (squadDto == null)
                {
                    return NotFound();
                }

                SquadViewModel squadViewModel = new SquadViewModel()
                {

RockstarsIT/RockstarsIT/Views/Squad/Create.cshtml
@model RockstarsIT.Models.CreateEditSquadViewModel

@{
    ViewData["Title"] = "Create";
}
<link rel="stylesheet" href="~/css/Squads.css/Index.css" />


@Model.Users.Count

<div class="create-container">
    <div class="inner-container">
        <h1>Nieuwe Squad Aanmaken</h1>

        <hr />
        <form asp-controller="Squad" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (ViewData["ErrorMessage"] != null)
            {
                <div class="text-danger">@ViewData["ErrorMessage"]</div>
            }
            <div class="form-group">
                <label class="control-label">Naam</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Beschrijving</label>
                @* <input asp-for="Description" class="form-control" /> *@
                <input textarea asp-for="Description" class="form-control" placeholder="Squad beschrijving invoeren">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Rockstars</label>
                <div style="display: flex;flex-direction: row; gap: 10px;">
                    <input id="emailInput" type="email" class="form-control" style="width: 85%" placeholder="Email">
                    <button type="button" onclick="addEmail()" style="width: 15%"
                        class="button button-primary">Add</button>
                </div>
                <span id="emailError" class="text-danger"></span>
            </div>

            <div class="form-group" id="emailList">
                <!-- Email list will be populated here -->
            </div>

            <input type="hidden" id="emailsJson" name="Emails" value="[]" />

            <div class="form-group">
                <input value="Aanmaken" type="submit" style="width: 100%" class="btn btn-primary" />
            </div>
        </form>
        <a asp-action="Index" class="btn btn-primary btn-lg">Back to List</a>

    </div>
</div>

@section Scripts {
    <script>
        let emails = [];

        function addEmail() {
            const emailInput = document.getElementById('emailInput');
            const emailError = document.getElementById('emailError');
            const email = emailInput.value.trim();


            // Check for duplicates
            if (emails.includes(email)) {
                emailError.textContent = 'This email is already added';
                return;
            }

            emails.push(email);
            updateEmailList();

            // Clear input and error
            emailInput.value = '';
            emailError.textContent = '';
        }

        function removeEmail(email) {
            emails = emails.filter(e => e !== email);
            updateEmailList();
        }

        function updateEmailList() {
            const emailList = document.getElementById('emailList');
            const emailsJson = document.getElementById('emailsJson');

            emailList.innerHTML = emails.map(email => `
                                    <div style="display: flex;flex-direction: row; gap: 10px; margin-bottom: 10px;">
                                        <input readonly style="width: 85%" value="${email}" class="form-control">
                                        <button type="button" onclick="removeEmail('${email}')" style="width: 15%" class="button button-secondary">Remove</button>
                                    </div>
                                `).join('');

            // Update hidden input with JSON string of emails
            emailsJson.value = JSON.stringify(emails);
        }
    </script>
}

RockstarsIT/RockstarsIT/Views/Squad/Delete.cshtml
@model RockstarsIT.Models.SquadViewModel

@{
    ViewData["Title"] = "Delete";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />

<div class="delete-container">
    <div class="inner-container">
        <h3>Weet je zeker dat je @Model.Name wilt verwijderen?</h3>
        <hr/>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id"/>
            <input type="submit" value="Bevestigen" class="btn btn-danger"/> |
            <a asp-action="Index">Terug</a>
        </form>
    </div>
</div>

RockstarsIT/RockstarsIT/Views/Squad/Details.cshtml
@model RockstarsIT.Models.SquadViewModel

@{
    ViewData["Title"] = @Model.Name;
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />

<div class="details-container">
    <div class="inner-container">
        <h4>@Model.Name</h4>
        
        <hr/>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="text-danger">@TempData["ErrorMessage"]</div>
            }
            <div class="form-group">
                <label asp-for="Name" class="control-label">Naam</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </form>
        <a class="btn bg-black text-white" asp-action="Index">Terug</a>
    </div>
</div>

RockstarsIT/RockstarsIT/Views/Squad/Edit.cshtml
@model RockstarsIT.Models.CreateEditSquadViewModel

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />



<div class="edit-container">
    <div class="inner-container">
        <h4>Bewerk @Model.Name</h4>

        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="text-danger">@TempData["ErrorMessage"]</div>
            }
            <div class="form-group">
                <label asp-for="Name" class="control-label">Naam</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rockstars</label>
                <div style="display: flex;flex-direction: row; gap: 10px;">
                    <input id="emailInput" type="email" class="form-control" style="width: 85%" placeholder="Email">
                    <button type="button" onclick="addEmail()" style="width: 15%"
                        class="button button-primary">Add</button>
                </div>
                <span id="emailError" class="text-danger"></span>
            </div>

            <div class="form-group" id="emailList">
                <!-- Email list will be populated here -->
            </div>

            <input type="hidden" id="emailsJson" name="Emails" value="[]" />
            <div class="form-group">
                <input type="hidden" asp-for="Id" value="@Model.Id" />
                <input type="submit" value="Opslaan" class="button button-primary button-full" />
            </div>
        </form>
        <br />
        <h5>Bedrijven</h5>
        <br />
        <div class="container" style="display: flex; flex-direction: row; gap: 15px; overflow-x: scroll;">
            @foreach (var item in Model.Companies)
            {
                if (item.Id == Model.Company?.Id)
                {
                    <form asp-controller="Squad" asp-action="DisconnectCompany" asp-route-companyId="@item.Id"
                        asp-route-squadId="@Model.Id" method="post">
                        <p>@item.Name</p>
                        <button type="submit" class="button button-secondary">Ontkoppel</button>
                    </form>
                }
                else
                {
                    <form asp-controller="Squad" asp-action="LinkCompany" asp-route-companyId="@item.Id"
                        asp-route-squadId="@Model.Id" method="post">
                        <p>@item.Name</p>
                        <button type="submit" class="button button-secondary">Linken</button>

                    </form>
                }
            }
        </div>
        <br />
        <a asp-action="Index">Terug</a>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<script>
    let emails = [];

    window.onload = function () {
            @foreach (var user in @Model.Users)
        {
            @:emails.push('@user.Email');
        }
                updateEmailList();
        };

        function addEmail() {
            const emailInput = document.getElementById('emailInput');
            const emailError = document.getElementById('emailError');
            const email = emailInput.value.trim();

            // Basic email validation

            // Check for duplicates
            if (emails.includes(email)) {
                emailError.textContent = 'This email is already added';
                return;
            }

            emails.push(email);
            updateEmailList();

            // Clear input and error
            emailInput.value = '';
            emailError.textContent = '';
        }

        function removeEmail(email) {
            emails = emails.filter(e => e !== email);
            updateEmailList();
        }

        function updateEmailList() {
            const emailList = document.getElementById('emailList');
            const emailsJson = document.getElementById('emailsJson');

            emailList.innerHTML = emails.map(email => `
                            <div style="display: flex;flex-direction: row; gap: 10px; margin-bottom: 10px;">
                                <input readonly style="width: 85%" value="${email}" class="form-control">
                                <button type="button" onclick="removeEmail('${email}')" style="width: 15%" class="button button-secondary">Remove</button>
                            </div>
                        `).join('');

            // Update hidden input with JSON string of emails
            emailsJson.value = JSON.stringify(emails);
        }
    </script>
}

RockstarsIT/RockstarsIT/Views/Squad/Index.cshtml
@model IEnumerable<RockstarsIT.Models.SquadViewModel>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/Squads.css/Index.css" />

<div class="header-container">
    <h2>Squads</h2>
    <a asp-action="Create" class="button button-primary">TOEVOEGEN</a>
</div>

<div class="dropdown">
    <button class="button button-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        @ViewBag.SelectedCompanyName
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        @if (ViewBag.Companies != null)
        {
            foreach (var company in ViewBag.Companies)
            {
                <li>
                    <a class="dropdown-item text-black text-decoration-none" href="#" data-company-id="@company.Id">@company.Name</a>
                </li>
            }
        }
        else
        {
            <li><a class="dropdown-item" href="#">Geen bedrijven beschikbaar</a></li>
        }
    </ul>
</div>

<div class="grid">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <div class="card">
                <a class="plus-button" asp-action="Edit" asp-route-id="@item.Id" aria-label="Add Item">+</a>
                <div class="card-header">
                    <h2>@item.Name</h2>
                </div>
                <div class="card-body">
                    <p>@item.Description</p>
                    @if (item.Company != null)
                    {
                        <p>Gekoppeld aan @item.Company.Name</p>
                    }
                    else
                    {
                        <p>Niet gekoppeld aan een bedrijf</p>
                    }
                    <div class="actions">
                        <a asp-action="Details" asp-route-id="@item.Id" class="button button-primary btn-sm">Details</a>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <p>Geen Squads gevonden.</p>
    }
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dropdownItems = document.querySelectorAll('.dropdown-item');
        const dropdownButton = document.getElementById('dropdownMenuButton');

        dropdownItems.forEach(item => {
            item.addEventListener('click', function () {
                const companyId = this.getAttribute('data-company-id');
                const companyName = this.textContent;

                // Werk de knoptekst bij
                dropdownButton.textContent = companyName;

                // Stuur de gebruiker door naar de gefilterde pagina
                window.location.href = `?companyId=${companyId}`;
            });
        });
    });
</script>